# -*- coding: utf-8 -*-
"""world-cup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/195ojLrjjDYOP0AvkqzNFqM6xQ8S9LeLg
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

results = pd.read_csv('results.csv')
elo = pd.read_csv('elo_ratings_wc2026.csv')
fixtures = pd.read_csv('wc_2026_fixtures.csv')
teams = pd.read_csv('wc_2026_teams.csv')

print("=== RESULTS ===")
print(results.shape)
print(results.head(3))

print("\n=== ELO ===")
print(elo.shape)
print(elo.head(3))

print("\n=== FIXTURES ===")
print(fixtures.shape)
print(fixtures.head(3))

print("\n=== TEAMS ===")
print(teams.shape)
print(teams.head(3))

# Convertir la date
results['date'] = pd.to_datetime(results['date'])

# Filtrer depuis 2000
results = results[results['date'] >= '2000-01-01']

print(results['tournament'].value_counts().head(20))

official_tournaments = [
    'FIFA World Cup',
    'FIFA World Cup qualification',
    'UEFA Euro',
    'UEFA Euro qualification',
    'Copa América',
    'African Cup of Nations',
    'African Cup of Nations qualification',
    'UEFA Nations League',
    'Gold Cup',
    'AFC Asian Cup',
    'AFC Asian Cup qualification',
    'CONCACAF Nations League'
]

results_filtered = results[results['tournament'].isin(official_tournaments)]

print(f"Avant : {len(results)} matchs")
print(f"Après : {len(results_filtered)} matchs")
print(results_filtered['tournament'].value_counts())

def get_result(row):
    if row['home_score'] > row['away_score']:
        return 'home_win'
    elif row['home_score'] < row['away_score']:
        return 'away_win'
    else:
        return 'draw'

results_filtered = results_filtered.copy()
results_filtered['result'] = results_filtered.apply(get_result, axis=1)

print(results_filtered['result'].value_counts())

# Garder seulement le dernier snapshot ELO par équipe
elo_latest = elo.sort_values('year').groupby('country').last().reset_index()

# Garder seulement les colonnes utiles
elo_latest = elo_latest[['country', 'rating', 'confederation']]

print(elo_latest.shape)
print(elo_latest.head(10))

# Merger ELO pour home team
results_filtered = results_filtered.merge(
    elo_latest[['country', 'rating']].rename(columns={'country': 'home_team', 'rating': 'home_elo'}),
    on='home_team', how='left'
)

# Merger ELO pour away team
results_filtered = results_filtered.merge(
    elo_latest[['country', 'rating']].rename(columns={'country': 'away_team', 'rating': 'away_elo'}),
    on='away_team', how='left'
)

print(results_filtered[['home_team', 'home_elo', 'away_team', 'away_elo', 'result']].head(10))
print(f"\nNaN home_elo: {results_filtered['home_elo'].isna().sum()}")
print(f"NaN away_elo: {results_filtered['away_elo'].isna().sum()}")

results_clean = results_filtered.dropna(subset=['home_elo', 'away_elo'])

print(f"Matchs restants : {len(results_clean)}")
print(results_clean['result'].value_counts())

# Reset — repartir de results_filtered sans ELO
results_filtered = results_filtered.drop(columns=['home_elo', 'away_elo'])

# Ajouter l'année dans results
results_filtered['year'] = results_filtered['date'].dt.year

# ELO par équipe par année
elo_by_year = elo[['country', 'year', 'rating']].copy()

# Merger home team
results_filtered = results_filtered.merge(
    elo_by_year.rename(columns={'country': 'home_team', 'rating': 'home_elo'}),
    on=['home_team', 'year'], how='left'
)

# Merger away team
results_filtered = results_filtered.merge(
    elo_by_year.rename(columns={'country': 'away_team', 'rating': 'away_elo'}),
    on=['away_team', 'year'], how='left'
)

print(f"NaN home_elo: {results_filtered['home_elo'].isna().sum()}")
print(f"NaN away_elo: {results_filtered['away_elo'].isna().sum()}")
print(f"Total matchs : {len(results_filtered)}")

results_filtered = results_filtered[results_filtered['date'] >= '2010-01-01']

print(f"Matchs depuis 2010 : {len(results_filtered)}")
print(results_filtered['tournament'].value_counts())

results_filtered = results[results['date'] >= '2006-01-01']
results_filtered = results_filtered[results_filtered['tournament'].isin(official_tournaments)]

print(f"Matchs depuis 2006 : {len(results_filtered)}")

# Target variable
results_filtered = results_filtered.copy()
results_filtered['result'] = results_filtered.apply(get_result, axis=1)
results_filtered['year'] = results_filtered['date'].dt.year

# ELO par année
elo_by_year = elo[['country', 'year', 'rating']].copy()

# Merger home ELO
results_filtered = results_filtered.merge(
    elo_by_year.rename(columns={'country': 'home_team', 'rating': 'home_elo'}),
    on=['home_team', 'year'], how='left'
)

# Merger away ELO
results_filtered = results_filtered.merge(
    elo_by_year.rename(columns={'country': 'away_team', 'rating': 'away_elo'}),
    on=['away_team', 'year'], how='left'
)

print(f"NaN home_elo: {results_filtered['home_elo'].isna().sum()}")
print(f"NaN away_elo: {results_filtered['away_elo'].isna().sum()}")
print(f"Total matchs : {len(results_filtered)}")

print(f"Années disponibles dans ELO : {elo['year'].min()} → {elo['year'].max()}")
print(f"Nombre d'équipes uniques : {elo['country'].nunique()}")
print(elo['year'].value_counts().sort_index().tail(10))

# Liste des 48 équipes qualifiées
wc_teams = teams['team'].tolist()
print(f"Nombre d'équipes : {len(wc_teams)}")
print(wc_teams)

wc_teams_official = [
    # Hosts
    'Canada', 'Mexico', 'USA',
    # AFC
    'Australia', 'Iraq', 'Iran', 'Japan', 'Jordan',
    'South Korea', 'Qatar', 'Saudi Arabia', 'Uzbekistan',
    # CAF
    'Algeria', 'Cape Verde', 'DR Congo', 'Ivory Coast',
    'Egypt', 'Ghana', 'Morocco', 'Senegal', 'South Africa', 'Tunisia',
    # CONCACAF
    'Curaçao', 'Haiti', 'Panama',
    # CONMEBOL
    'Argentina', 'Brazil', 'Colombia', 'Ecuador', 'Paraguay', 'Uruguay',
    # OFC
    'New Zealand',
    # UEFA
    'Austria', 'Belgium', 'Bosnia and Herzegovina', 'Croatia',
    'Czechia', 'England', 'France', 'Germany', 'Netherlands',
    'Norway', 'Portugal', 'Scotland', 'Spain', 'Sweden',
    'Switzerland', 'Türkiye'
]

print(f"Total équipes : {len(wc_teams_official)}")

# Filtrer seulement les matchs entre équipes du WC 2026
results_wc = results_filtered[
    (results_filtered['home_team'].isin(wc_teams_official)) &
    (results_filtered['away_team'].isin(wc_teams_official))
].copy()

print(f"Matchs entre équipes WC 2026 : {len(results_wc)}")
print(results_wc['result'].value_counts())

# Stats de base
print(f"Total matchs pour training : {len(results_filtered)}")
print(f"Equipes uniques : {results_filtered['home_team'].nunique()}")

# Vérifier que nos 48 équipes sont bien présentes
teams_in_data = set(results_filtered['home_team'].tolist() + results_filtered['away_team'].tolist())
missing = [t for t in wc_teams_official if t not in teams_in_data]
print(f"\nEquipes WC manquantes dans la data : {missing}")

# Renommer dans results_filtered
name_mapping = {
    'United States': 'USA',
    'Czech Republic': 'Czechia',
    'Turkey': 'Türkiye'
}

results_filtered['home_team'] = results_filtered['home_team'].replace(name_mapping)
results_filtered['away_team'] = results_filtered['away_team'].replace(name_mapping)

# Vérifier
teams_in_data = set(results_filtered['home_team'].tolist() + results_filtered['away_team'].tolist())
missing = [t for t in wc_teams_official if t not in teams_in_data]
print(f"Equipes WC manquantes : {missing}")

def get_team_stats(team, date, df, n=10):
    # Matchs de cette équipe avant cette date
    matches = df[
        ((df['home_team'] == team) | (df['away_team'] == team)) &
        (df['date'] < date)
    ].tail(n)

    if len(matches) == 0:
        return {'win_rate': 0.5, 'avg_goals_scored': 1.0, 'avg_goals_conceded': 1.0}

    wins, goals_scored, goals_conceded = 0, 0, 0

    for _, row in matches.iterrows():
        if row['home_team'] == team:
            goals_scored += row['home_score']
            goals_conceded += row['away_score']
            if row['result'] == 'home_win':
                wins += 1
        else:
            goals_scored += row['away_score']
            goals_conceded += row['home_score']
            if row['result'] == 'away_win':
                wins += 1

    n_matches = len(matches)
    return {
        'win_rate': wins / n_matches,
        'avg_goals_scored': goals_scored / n_matches,
        'avg_goals_conceded': goals_conceded / n_matches
    }

# Test sur une équipe
print(get_team_stats('France', '2026-01-01', results_filtered))

from tqdm import tqdm

features = []

for _, row in tqdm(results_filtered.iterrows(), total=len(results_filtered)):
    home_stats = get_team_stats(row['home_team'], row['date'], results_filtered)
    away_stats = get_team_stats(row['away_team'], row['date'], results_filtered)

    features.append({
        'home_win_rate': home_stats['win_rate'],
        'home_goals_scored': home_stats['avg_goals_scored'],
        'home_goals_conceded': home_stats['avg_goals_conceded'],
        'away_win_rate': away_stats['win_rate'],
        'away_goals_scored': away_stats['avg_goals_scored'],
        'away_goals_conceded': away_stats['avg_goals_conceded'],
        'result': row['result']
    })

df_features = pd.DataFrame(features)
print(df_features.shape)
print(df_features.head())

print(df_features.iloc[5000:5005])
print("\n")
print(df_features.tail())

# Ajouter ELO difference comme feature
elo_latest = elo[elo['year'] == 2025][['country', 'rating']].copy()

# Merger ELO dans results_filtered
results_filtered = results_filtered.drop(columns=['home_elo', 'away_elo'], errors='ignore')

results_filtered = results_filtered.merge(
    elo_latest.rename(columns={'country': 'home_team', 'rating': 'home_elo'}),
    on='home_team', how='left'
)
results_filtered = results_filtered.merge(
    elo_latest.rename(columns={'country': 'away_team', 'rating': 'away_elo'}),
    on='away_team', how='left'
)

# Ajouter ELO dans df_features
df_features['home_elo'] = results_filtered['home_elo'].values
df_features['away_elo'] = results_filtered['away_elo'].values
df_features['elo_diff'] = df_features['home_elo'] - df_features['away_elo']

# Remplir les NaN
df_features['avg_goals_scored'] = df_features['home_goals_scored'].fillna(df_features['home_goals_scored'].mean())
df_features['home_goals_scored'] = df_features['home_goals_scored'].fillna(df_features['home_goals_scored'].mean())
df_features['away_goals_scored'] = df_features['away_goals_scored'].fillna(df_features['away_goals_scored'].mean())
df_features['home_goals_conceded'] = df_features['home_goals_conceded'].fillna(df_features['home_goals_conceded'].mean())
df_features['away_goals_conceded'] = df_features['away_goals_conceded'].fillna(df_features['away_goals_conceded'].mean())

print(df_features.isnull().sum())
print(df_features.shape)

mean_elo = elo_latest['rating'].mean()

df_features['home_elo'] = df_features['home_elo'].fillna(mean_elo)
df_features['away_elo'] = df_features['away_elo'].fillna(mean_elo)
df_features['elo_diff'] = df_features['home_elo'] - df_features['away_elo']

print(df_features.isnull().sum())
print(f"\nMean ELO utilisé : {mean_elo:.0f}")
print(df_features.head())

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

# Features et target
feature_cols = [
    'home_win_rate', 'home_goals_scored', 'home_goals_conceded',
    'away_win_rate', 'away_goals_scored', 'away_goals_conceded',
    'home_elo', 'away_elo', 'elo_diff'
]

X = df_features[feature_cols]
y = df_features['result']

# Encoder la target
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Split train/test
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Entraîner
model = XGBClassifier(n_estimators=200, max_depth=5, learning_rate=0.05, random_state=42)
model.fit(X_train, y_train)

# Evaluer
y_pred = model.predict(X_test)
print(f"Accuracy : {accuracy_score(y_test, y_pred):.3f}")
print(classification_report(y_test, y_pred, target_names=le.classes_))

# FIFA rank depuis wc_2026_teams
fifa_ranks = teams[['team', 'fifa_rank']].copy()

# Merger pour home team
results_filtered = results_filtered.merge(
    fifa_ranks.rename(columns={'team': 'home_team', 'fifa_rank': 'home_fifa_rank'}),
    on='home_team', how='left'
)

# Merger pour away team
results_filtered = results_filtered.merge(
    fifa_ranks.rename(columns={'team': 'away_team', 'fifa_rank': 'away_fifa_rank'}),
    on='away_team', how='left'
)

# Remplir NaN avec rang moyen
mean_rank = fifa_ranks['fifa_rank'].mean()
results_filtered['home_fifa_rank'] = results_filtered['home_fifa_rank'].fillna(mean_rank)
results_filtered['away_fifa_rank'] = results_filtered['away_fifa_rank'].fillna(mean_rank)

print(results_filtered[['home_team', 'home_fifa_rank', 'away_team', 'away_fifa_rank']].head(10))

# Ajouter FIFA rank dans df_features
df_features['home_fifa_rank'] = results_filtered['home_fifa_rank'].values
df_features['away_fifa_rank'] = results_filtered['away_fifa_rank'].values
df_features['fifa_rank_diff'] = df_features['away_fifa_rank'] - df_features['home_fifa_rank']

# Step 2 — Pondération par date (matchs récents = plus de poids)
df_features['date'] = results_filtered['date'].values
df_features['date'] = pd.to_datetime(df_features['date'])

max_date = df_features['date'].max()
df_features['days_ago'] = (max_date - df_features['date']).dt.days
df_features['weight'] = 1 / (1 + df_features['days_ago'] / 365)

print(df_features[['date', 'days_ago', 'weight', 'home_fifa_rank', 'away_fifa_rank', 'fifa_rank_diff']].head(10))
print(f"\nWeight min : {df_features['weight'].min():.3f}")
print(f"Weight max : {df_features['weight'].max():.3f}")

feature_cols = [
    'home_win_rate', 'home_goals_scored', 'home_goals_conceded',
    'away_win_rate', 'away_goals_scored', 'away_goals_conceded',
    'home_elo', 'away_elo', 'elo_diff',
    'home_fifa_rank', 'away_fifa_rank', 'fifa_rank_diff'
]

X = df_features[feature_cols]
y = df_features['result']
weights = df_features['weight']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test, w_train, w_test = train_test_split(
    X, y_encoded, weights, test_size=0.2, random_state=42
)

model = XGBClassifier(n_estimators=200, max_depth=5, learning_rate=0.05, random_state=42)
model.fit(X_train, y_train, sample_weight=w_train)

y_pred = model.predict(X_test)
print(f"Accuracy : {accuracy_score(y_test, y_pred):.3f}")
print(classification_report(y_test, y_pred, target_names=le.classes_))

from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.8, 1.0]
}

grid_search = GridSearchCV(
    XGBClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train, sample_weight=w_train)

print(f"Meilleurs params : {grid_search.best_params_}")
print(f"Meilleur score CV : {grid_search.best_score_:.3f}")

# Evaluer sur test set
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)
print(f"\nAccuracy test : {accuracy_score(y_test, y_pred):.3f}")
print(classification_report(y_test, y_pred, target_names=le.classes_))

tournament_weights = {
    'FIFA World Cup': 3.0,
    'Copa América': 2.5,
    'UEFA Euro': 2.5,
    'African Cup of Nations': 2.5,
    'AFC Asian Cup': 2.5,
    'Gold Cup': 2.0,
    'UEFA Nations League': 2.0,
    'CONCACAF Nations League': 2.0,
    'FIFA World Cup qualification': 1.5,
    'UEFA Euro qualification': 1.5,
    'African Cup of Nations qualification': 1.5,
    'AFC Asian Cup qualification': 1.5,
}

results_filtered['tournament_weight'] = results_filtered['tournament'].map(tournament_weights)

print(results_filtered[['tournament', 'tournament_weight']].drop_duplicates())

def get_team_stats_v2(team, date, df, n=10):
    matches = df[
        ((df['home_team'] == team) | (df['away_team'] == team)) &
        (df['date'] < date)
    ].tail(n)

    if len(matches) == 0:
        return {
            'win_rate': 0.5,
            'avg_goals_scored': 1.0,
            'avg_goals_conceded': 1.0
        }

    wins, goals_scored, goals_conceded, total_weight = 0, 0, 0, 0

    for _, row in matches.iterrows():
        w = row['tournament_weight']
        total_weight += w
        if row['home_team'] == team:
            goals_scored += row['home_score'] * w
            goals_conceded += row['away_score'] * w
            if row['result'] == 'home_win':
                wins += w
        else:
            goals_scored += row['away_score'] * w
            goals_conceded += row['home_score'] * w
            if row['result'] == 'away_win':
                wins += w

    return {
        'win_rate': wins / total_weight,
        'avg_goals_scored': goals_scored / total_weight,
        'avg_goals_conceded': goals_conceded / total_weight
    }

def get_h2h(home_team, away_team, date, df):
    matches = df[
        (((df['home_team'] == home_team) & (df['away_team'] == away_team)) |
         ((df['home_team'] == away_team) & (df['away_team'] == home_team))) &
        (df['date'] < date)
    ].tail(10)

    if len(matches) == 0:
        return 0.5

    home_wins = 0
    for _, row in matches.iterrows():
        if (row['home_team'] == home_team and row['result'] == 'home_win') or \
           (row['away_team'] == home_team and row['result'] == 'away_win'):
            home_wins += 1

    return home_wins / len(matches)

# Test
print(get_team_stats_v2('France', '2026-01-01', results_filtered))
print(f"H2H France vs Brazil : {get_h2h('France', 'Brazil', '2026-01-01', results_filtered):.2f}")

features_v2 = []

for _, row in tqdm(results_filtered.iterrows(), total=len(results_filtered)):
    home_stats = get_team_stats_v2(row['home_team'], row['date'], results_filtered)
    away_stats = get_team_stats_v2(row['away_team'], row['date'], results_filtered)
    h2h = get_h2h(row['home_team'], row['away_team'], row['date'], results_filtered)

    features_v2.append({
        'home_win_rate': home_stats['win_rate'],
        'home_goals_scored': home_stats['avg_goals_scored'],
        'home_goals_conceded': home_stats['avg_goals_conceded'],
        'away_win_rate': away_stats['win_rate'],
        'away_goals_scored': away_stats['avg_goals_scored'],
        'away_goals_conceded': away_stats['avg_goals_conceded'],
        'h2h_home_win_rate': h2h,
        'result': row['result']
    })

df_features_v2 = pd.DataFrame(features_v2)
print(df_features_v2.shape)
print(df_features_v2.head())

# Ajouter ELO et FIFA rank
df_features_v2['home_elo'] = df_features['home_elo'].values
df_features_v2['away_elo'] = df_features['away_elo'].values
df_features_v2['elo_diff'] = df_features_v2['home_elo'] - df_features_v2['away_elo']
df_features_v2['home_fifa_rank'] = df_features['home_fifa_rank'].values
df_features_v2['away_fifa_rank'] = df_features['away_fifa_rank'].values
df_features_v2['fifa_rank_diff'] = df_features_v2['away_fifa_rank'] - df_features_v2['home_fifa_rank']
df_features_v2['weight'] = df_features['weight'].values

# Entraîner
feature_cols_v2 = [
    'home_win_rate', 'home_goals_scored', 'home_goals_conceded',
    'away_win_rate', 'away_goals_scored', 'away_goals_conceded',
    'h2h_home_win_rate', 'home_elo', 'away_elo', 'elo_diff',
    'home_fifa_rank', 'away_fifa_rank', 'fifa_rank_diff'
]

X = df_features_v2[feature_cols_v2]
y = le.fit_transform(df_features_v2['result'])

X_train, X_test, y_train, y_test, w_train, w_test = train_test_split(
    X, y, df_features_v2['weight'], test_size=0.2, random_state=42
)

model_v2 = XGBClassifier(learning_rate=0.01, max_depth=5, n_estimators=300, subsample=0.8, random_state=42)
model_v2.fit(X_train, y_train, sample_weight=w_train)

y_pred = model_v2.predict(X_test)
print(f"Accuracy : {accuracy_score(y_test, y_pred):.3f}")
print(classification_report(y_test, y_pred, target_names=le.classes_))

import joblib

joblib.dump(model_v2, 'model.joblib')
joblib.dump(le, 'label_encoder.joblib')
joblib.dump(feature_cols_v2, 'feature_cols.joblib')

print("Modèle sauvegardé !")
print(f"Classes : {le.classes_}")
print(f"Features : {feature_cols_v2}")

# Stats actuelles pour chaque équipe WC 2026
team_stats = {}

for team in wc_teams_official:
    stats = get_team_stats_v2(team, '2026-06-11', results_filtered)
    elo_row = elo_latest[elo_latest['country'] == team]
    elo_val = elo_row['rating'].values[0] if len(elo_row) > 0 else mean_elo

    team_stats[team] = {
        'win_rate': stats['win_rate'],
        'avg_goals_scored': stats['avg_goals_scored'],
        'avg_goals_conceded': stats['avg_goals_conceded'],
        'elo': elo_val
    }

print(f"Equipes préparées : {len(team_stats)}")
print(team_stats['France'])
print(team_stats['Argentina'])

import numpy as np
import random

def predict_match(home_team, away_team, team_stats, fifa_ranks, model, le, feature_cols):
    home = team_stats[home_team]
    away = team_stats[away_team]

    home_rank = fifa_ranks.get(home_team, mean_rank)
    away_rank = fifa_ranks.get(away_team, mean_rank)
    h2h = get_h2h(home_team, away_team, '2026-06-11', results_filtered)

    features = pd.DataFrame([{
        'home_win_rate': home['win_rate'],
        'home_goals_scored': home['avg_goals_scored'],
        'home_goals_conceded': home['avg_goals_conceded'],
        'away_win_rate': away['win_rate'],
        'away_goals_scored': away['avg_goals_scored'],
        'away_goals_conceded': away['avg_goals_conceded'],
        'h2h_home_win_rate': h2h,
        'home_elo': home['elo'],
        'away_elo': away['elo'],
        'elo_diff': home['elo'] - away['elo'],
        'home_fifa_rank': home_rank,
        'away_fifa_rank': away_rank,
        'fifa_rank_diff': away_rank - home_rank
    }])

    probs = model.predict_proba(features[feature_cols])[0]
    classes = le.classes_

    prob_dict = dict(zip(classes, probs))

    # Tirer un résultat aléatoire basé sur les probabilités
    outcome = random.choices(
        ['away_win', 'draw', 'home_win'],
        weights=[prob_dict['away_win'], prob_dict['draw'], prob_dict['home_win']]
    )[0]

    if outcome == 'home_win':
        return home_team
    elif outcome == 'away_win':
        return away_team
    else:
        # En cas de draw en knockout → tirage aléatoire 50/50
        return random.choice([home_team, away_team])

# FIFA ranks dict
fifa_ranks_dict = dict(zip(teams['team'], teams['fifa_rank']))

# Test
winner = predict_match('France', 'Brazil', team_stats, fifa_ranks_dict, model_v2, le, feature_cols_v2)
print(f"Vainqueur prédit : {winner}")

def simulate_tournament(fixtures, team_stats, fifa_ranks_dict, model, le, feature_cols):
    # Phase de groupes
    group_points = {team: 0 for team in wc_teams_official}
    group_gd = {team: 0 for team in wc_teams_official}

    group_matches = fixtures[fixtures['stage'] == 'Group Stage']

    for _, match in group_matches.iterrows():
        home = match['team1']
        away = match['team2']

        if home not in team_stats or away not in team_stats:
            continue

        home_s = team_stats[home]
        away_s = team_stats[away]
        h2h = get_h2h(home, away, '2026-06-11', results_filtered)

        features = pd.DataFrame([{
            'home_win_rate': home_s['win_rate'],
            'home_goals_scored': home_s['avg_goals_scored'],
            'home_goals_conceded': home_s['avg_goals_conceded'],
            'away_win_rate': away_s['win_rate'],
            'away_goals_scored': away_s['avg_goals_scored'],
            'away_goals_conceded': away_s['avg_goals_conceded'],
            'h2h_home_win_rate': h2h,
            'home_elo': home_s['elo'],
            'away_elo': away_s['elo'],
            'elo_diff': home_s['elo'] - away_s['elo'],
            'home_fifa_rank': fifa_ranks_dict.get(home, mean_rank),
            'away_fifa_rank': fifa_ranks_dict.get(away, mean_rank),
            'fifa_rank_diff': fifa_ranks_dict.get(away, mean_rank) - fifa_ranks_dict.get(home, mean_rank)
        }])

        probs = model.predict_proba(features[feature_cols])[0]
        classes = le.classes_
        prob_dict = dict(zip(classes, probs))

        outcome = random.choices(
            ['away_win', 'draw', 'home_win'],
            weights=[prob_dict['away_win'], prob_dict['draw'], prob_dict['home_win']]
        )[0]

        if outcome == 'home_win':
            group_points[home] += 3
            group_gd[home] += 1
        elif outcome == 'away_win':
            group_points[away] += 3
            group_gd[away] += 1
        else:
            group_points[home] += 1
            group_points[away] += 1

    # Qualifier top 2 par groupe
    groups = fixtures[fixtures['stage'] == 'Group Stage']['group'].unique()
    qualified = []

    for group in groups:
        group_teams = fixtures[
            (fixtures['stage'] == 'Group Stage') &
            (fixtures['group'] == group)
        ][['team1', 'team2']].values.flatten()
        group_teams = list(set(group_teams))
        group_teams = [t for t in group_teams if t in team_stats]

        group_teams.sort(key=lambda t: (group_points[t], group_gd[t]), reverse=True)
        qualified.extend(group_teams[:2])

    # Phase knockout
    knockout_teams = qualified.copy()

    while len(knockout_teams) > 1:
        next_round = []
        random.shuffle(knockout_teams)
        for i in range(0, len(knockout_teams), 2):
            if i+1 < len(knockout_teams):
                winner = predict_match(
                    knockout_teams[i], knockout_teams[i+1],
                    team_stats, fifa_ranks_dict, model, le, feature_cols
                )
                next_round.append(winner)
        knockout_teams = next_round

    return knockout_teams[0] if knockout_teams else None

# Test une simulation
winner = simulate_tournament(fixtures, team_stats, fifa_ranks_dict, model_v2, le, feature_cols_v2)
print(f"Vainqueur simulé : {winner}")

from collections import Counter

N_SIMULATIONS = 10000
winners = []

for _ in tqdm(range(N_SIMULATIONS)):
    winner = simulate_tournament(fixtures, team_stats, fifa_ranks_dict, model_v2, le, feature_cols_v2)
    if winner:
        winners.append(winner)

# Calculer les probabilités
win_counts = Counter(winners)
win_probs = {team: count/N_SIMULATIONS*100 for team, count in win_counts.items()}
win_probs = dict(sorted(win_probs.items(), key=lambda x: x[1], reverse=True))

print("\n🏆 TOP 10 FAVORIS WC 2026 :")
for i, (team, prob) in enumerate(list(win_probs.items())[:10], 1):
    print(f"{i}. {team}: {prob:.1f}%")

